### ISSUE TITLE
homebrew versions 

### ISSUE THREAD

**Issue by stevenjgilmore** [vmtk/vmtk#180]
Hi, below is the output from `brew info` and `brew upgrade vmtk`.

Is there a way to get the newest release (v1.3.2)? I am currently encountering issues with vmtkSurfaceViewer (and the other graphical functions) on a Sierra machine. Based on the release notes from v1.3.2, this new version may assist in that, but I can not figure out how to upgrade via homebrew. 

```
$ brew info vmtk
vmtk: stable 1.3.1, HEAD
The Vascular Modeling Toolkit
http://www.vmtk.org
/usr/local/Cellar/vmtk/1.3.1_1 (535 files, 23.4MB) *
  Built from source on 2017-06-06 at 13:06:19
From: /usr/local/opt/vmtk/.brew/vmtk.rb
==> Dependencies
Build: cmake ✔
Required: vtk ✔, insightToolkit ✔
==> Requirements
Required: python ✔
```

```
$ brew upgrade vmtk
Error: vmtk 1.3.1_1 already installed
```
I have also tried using the command: 
```
$ brew install https://raw.githubusercontent.com/vmtk/vmtk/v1.3.2/distribution/homebrew/vmtk.rb
Warning: vmtk 1.3.1_1 is already installed
``` 
Assistance much appreciated. Here is my brew config information , for completeness. 

```
$ brew --config
HOMEBREW_VERSION: 1.2.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 54e01d76db34a3a649c79b189873bfd0a52dbc9f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f408de223af34396720c61d7f047f0ec1ed068bb
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by rlizzo** [comment]
Hi @stevenjgilmore,

Before installing the latest release (v1.3.2), you need to first uninstall the old version of VMTK. 

Please see the instructions at http://www.vmtk.org/download/ for Mac OSX. 

Let us know if this solves your problem.

**Comment by stevenjgilmore** [comment]
Hi @rlizzo, thanks for the response. Those were the instructions that I was following. Here is my output, it still installs v1.3.1

After uninstalling:
```
$ brew info vmtk
Error: No available formula with the name "vmtk"
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
```
Try to install: 
``` 
$ brew install https://raw.githubusercontent.com/vmtk/vmtk/v1.3.2/distribution/homebrew/vmtk.rb
######################################################################## 100.0%
==> Installing dependencies for vmtk: vtk, insightToolkit
==> Installing vmtk dependency: vtk
==> Downloading https://homebrew.bintray.com/bottles-science/vtk-7.1.1_1.sierra.bottle.tar.gz
Already downloaded: /var/.home/admin/Library/Caches/Homebrew/vtk-7.1.1_1.sierra.bottle.tar.gz
==> Pouring vtk-7.1.1_1.sierra.bottle.tar.gz
==> Caveats
Even without the --with-qt5 option, you can display native VTK render windows
from python. Alternatively, you can integrate the RenderWindowInteractor
in PyQt4, Tk or Wx at runtime. Read more:
    import vtk.qt5; help(vtk.qt5) or import vtk.wx; help(vtk.wx)
==> Summary
🍺  /usr/local/Cellar/vtk/7.1.1_1: 3,334 files, 109.7MB
==> Installing vmtk dependency: insightToolkit
==> Downloading https://homebrew.bintray.com/bottles-science/insighttoolkit-4.12.0.sierra.bottle.tar.gz
Already downloaded: /var/.home/admin/Library/Caches/Homebrew/insighttoolkit-4.12.0.sierra.bottle.tar.gz
==> Pouring insighttoolkit-4.12.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/insighttoolkit/4.12.0: 4,491 files, 69.7MB
==> Installing vmtk
==> Downloading https://github.com/vmtk/vmtk/archive/v1.3.1.tar.gz
==> Downloading from https://codeload.github.com/vmtk/vmtk/tar.gz/v1.3.1
######################################################################## 100.0%
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/vmtk/1.3.1_1 -DCMAKE_BUILD_TYPE=Release
==> make
==> make install
🍺  /usr/local/Cellar/vmtk/1.3.1_1: 535 files, 23.4MB, built in 51 seconds
``` 
After install:
``` 
$ brew info vmtk
vmtk: stable 1.3.1, HEAD
The Vascular Modeling Toolkit
http://www.vmtk.org
/usr/local/Cellar/vmtk/1.3.1_1 (535 files, 23.4MB) *
  Built from source on 2017-06-07 at 13:06:57
From: /usr/local/opt/vmtk/.brew/vmtk.rb
==> Dependencies
Build: cmake ✔
Required: vtk ✔, insightToolkit ✔
==> Requirements
Required: python ✔
```

**Comment by stevenjgilmore** [comment]
Hm, I was able to hack the upgrade by replacing my `./brew/vmtk.rb` with the newest version from: https://github.com/vmtk/vmtk/blob/master/distribution/homebrew/vmtk.rb 

Still not sure why brew is not recognizing the newest release on a `brew update` call. 

Current status: the GUI commands such as `vmtksurfaceviewer` work when called from terminal but do not work when called from Pypes.

**Comment by rlizzo** [comment]
Thanks for the update @stevenjgilmore. I'm not entirely sure why `brew update` isn't working either, any feedback @lantiga? In any case this should be a moot point in the near future as we are planning a move the packaging via anaconda, which should be ready in the next few weeks. 

Do you recieve any errors or a traceback when calling `vmtksurfaceviewer` from PypePad? If so, can you share it with us?

**Comment by lantiga** [comment]
Hi @stevenjgilmore, I think it's my fault with the recent back and forth on brew. Can you please try this command?
```
brew install https://gist.githubusercontent.com/lantiga/64b89fbb1f2ce5875bb21558d1599811/raw/b232e485a5deaedbe494670d44f685b053d97b19/vmtk.rb
```
Thanks! (and thanks @rlizzo)

**Comment by lantiga** [comment]
Also, @stevenjgilmore please let me know if this works for you, I'll update the docs accordingly.

**Comment by stevenjgilmore** [comment]
@lantiga , I uninstalled vmtk with `brew uninstall --force vmtk` and tried the command that you suggested. Below is the error that I am getting. Not sure what happened, since this was at a working state previously. 

```
$ brew install https://gist.githubusercontent.com/lantiga/64b89fbb1f2ce5875bb21558d1599811/raw/b232e485a5deaedbe494670d44f685b053d97b19/vmtk.rb 
==> Downloading https://github.com/vmtk/vmtk/archive/v1.3.2.tar.gz
==> Downloading from https://codeload.github.com/vmtk/vmtk/tar.gz/v1.3.2
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/vmtk/1.3.2_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_RPATH:STRING=/usr/local/Cellar/vmtk/1.3.2_1/lib -DCMAKE_INSTALL_NAME_DIR:STRING=/usr/local/Cellar/vmtk/1.3.2_1/lib .. -DUSE_SYSTEM_ITK=ON -DITK_DIR=/usr/local/Cellar/insighttoolkit/4.9.0 -DUSE_SYSTEM_VTK=ON -DVTK_DIR=/usr/local/Cellar/vtk/7.1.0 -DVMTK_USE_SUPERBUILD=OFF -DUSE_VTK6_SUPERBUILD=OFF -DVMTK_USE_RENDERING=ON -DVTK_WRAP_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python
 -DPYTHON_LIBRARY='/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib' -DPYTHON_INCLUDE_DIR='/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7' ..
==> make
Last 15 lines from /var/.home/admin/Library/Logs/Homebrew/vmtk/02.make:
  int FillInputPortInformation(int port, vtkInformation* info) VTK_OVERRIDE;
      ^
In file included from /tmp/vmtk-20170707-68136-19ct3cu/vmtk-1.3.2/build/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3DPython.cxx:11:
/tmp/vmtk-20170707-68136-19ct3cu/vmtk-1.3.2/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3D.h:63:15: warning: 'RequestData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int RequestData(vtkInformation *, vtkInformationVector **, vtkInformationVector *);
              ^
/usr/local/Cellar/vtk/8.0.0/include/vtk-8.0/vtkPolyDataAlgorithm.h:103:15: note: overridden virtual function is here
  virtual int RequestData(vtkInformation* request,
              ^
3 warnings generated.
[ 46%] Linking CXX shared library ../../bin/libvtkvmtkComputationalGeometryPythonD.dylib
cd /tmp/vmtk-20170707-68136-19ct3cu/vmtk-1.3.2/build/vtkVmtk/ComputationalGeometry && /usr/local/Cellar/cmake/3.8.2/bin/cmake -E cmake_link_script CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/link.txt --verbose=1
/usr/bin/g++    -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.12 -dynamiclib -Wl,-headerpad_max_install_names -Wl,-dylib_file,/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib  -o ../../bin/libvtkvmtkComputationalGeometryPythonD.dylib -install_name /tmp/vmtk-20170707-68136-19ct3cu/vmtk-1.3.2/build/bin/libvtkvmtkComputationalGeometryPythonD.dylib CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkAppendFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCapPolyDataPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineAttributesFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBifurcationVectorsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBifurcationReferenceSystemsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBranchExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBranchGeometryPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineEndpointExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineGeometryPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineReferenceSystemAttributesOffsetPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSmoothingPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSphereDistancePython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSplitExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSplittingAndGroupingFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineUtilitiesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkBoundaryReferenceSystemsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkInternalTetrahedraExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkMergeCenterlinesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkMinHeapPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkNonManifoldFastMarchingPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkNonManifoldSteepestDescentPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyBallPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyBallLinePython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyBallModellerPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBifurcationSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBifurcationProfilesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBoundaryExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBranchSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBranchUtilitiesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlinesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineGroupsClipperPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineAbscissaMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineAngularMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineProjectionPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataFlowExtensionsFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataDistanceToCenterlinesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataLineEmbedderPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataLocalGeometryPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataPatchingFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataReferenceSystemBoundaryMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataScissorsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataStretchMappingFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkReferenceSystemUtilitiesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkSimplifyVoronoiDiagramPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkSteepestDescentLineTracerPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkSteepestDescentShooterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkUnstructuredGridCenterlineGroupsClipperPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkUnstructuredGridCenterlineSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkVoronoiDiagram3DPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkComputationalGeometryPythonInitImpl.cxx.o  -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenCL.framework  -L/usr/local/lib  -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries  -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenCL.framework -Wl,-rpath,/usr/local/lib ../../bin/libvtkvmtkComputationalGeometry.dylib /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkFiltersGeneralPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonComputationalGeometryPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkFiltersCorePython27D-8.0.1.dylib ../../bin/libvtkvmtkCommon.dylib /System/Library/Frameworks/Python.framework/Versions/2.7/Python /usr/local/Cellar/vtk/8.0.0/lib/libvtkWrappingTools-8.0.a /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonExecutionModelPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonDataModelPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonTransformsPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonMiscPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonMathPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonSystemPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonCorePython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkWrappingPython27Core-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkFiltersGeneral-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonComputationalGeometry-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkFiltersCore-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonExecutionModel-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonDataModel-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonTransforms-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonMisc-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonMath-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonSystem-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtkCommonCore-8.0.1.dylib /usr/local/Cellar/vtk/8.0.0/lib/libvtksys-8.0.1.dylib 
[ 46%] Built target vtkvmtkComputationalGeometryPythonD
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

```

**Comment by lantiga** [comment]
Thanks for the report, I see that brew now picks up VTK 8.0. 
I just merged #188 (cc @deparis), can you try again?

**Comment by stevenjgilmore** [comment]
Hi @lantiga , I've tried uninstalling and reinstalling `vmtk` a few different ways yesterday - I am still getting the same error as my last post. 

It does indeed pick up VTK 8.0 - that is currently the only version of vtk installed on my machine: 
```
$ brew info vtk
homebrew/science/vtk: stable 8.0.0 (bottled), HEAD
Toolkit for 3D computer graphics, image processing, and visualization.
http://www.vtk.org
/usr/local/Cellar/vtk/8.0.0 (3,441 files, 117.2MB) *
  Poured from bottle on 2017-07-09 at 13:26:28
From: https://github.com/Homebrew/homebrew-science/blob/master/vtk.rb
```

**Comment by deparis** [comment]
Quick fix:

You have to change the git version: 

`wget https://github.com/Homebrew/homebrew-science/blob/master/vtk.rb`

in vmtk.rb, 3rd and 4th line
`url "https://github.com/vmtk/vmtk.git" `
`  version "1.4.1" `

(for example). And then 
`brew install vmtk.rb`

General fix: This has to be fixed by the maintainers.

**Comment by stevenjgilmore** [comment]
So using vmtk version 1.4.1 and vtk version 8.0.0, I get this error when trying to run a basic vmtk command: 
```
$ vmtkcenterlines 

No module named vtkvmtkCommonPython
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/vmtk/pypeserver.py", line 45, in RunPypeProcess
  File "/usr/local/lib/python2.7/site-packages/vmtk/pype.py", line 245, in Execute
  File "/usr/local/lib/python2.7/site-packages/vmtk/pype.py", line 65, in PrintError
RuntimeError: No module named vtkvmtkCommonPython
```

In a different attempt, I was able to back install vtk v7.1.1_1 but when I `brew install vmtk` it does not recognize my version of `vtk` and tries to download v8.0.0. Note the vtk dependency in the below output. 
```
$ brew info vtk 
Password:
homebrew/science/vtk: stable 8.0.0 (bottled), HEAD
Toolkit for 3D computer graphics, image processing, and visualization.
http://www.vtk.org
/usr/local/Cellar/vtk/7.1.1_1 (3,461 files, 110MB) *
  Built from source on 2017-07-10 at 15:27:27
From: https://github.com/Homebrew/homebrew-science/blob/master/vtk.rb
==> Dependencies
Build: cmake ✔
Required: netcdf ✔
Recommended: boost ✔, fontconfig ✔, hdf5 ✔, jpeg ✔, libpng ✔, libtiff ✔
Optional: qt ✘
 ... 

$ brew info vmtk 
vmtk: stable 1.3.1, HEAD
The Vascular Modeling Toolkit
http://www.vmtk.org
Not installed
From: /var/.home/admin/Library/Caches/Homebrew/Formula/vmtk.rb
==> Dependencies
Build: cmake ✔
Required: vtk ✘, insightToolkit ✔
==> Requirements
Required: python ✔
```

**Comment by stevenew83** [comment]
Hi, I recently did `brew update` and `brew upgrade` and also found that vtk v8 problem. I've now tried a fresh install of both via home-brew and get these errors:

Firstly, `brew install https://raw.githubusercontent.com/vmtk/vmtk/v1.3.2/distribution/homebrew/vmtk.rb` results in:

`Last 15 lines from /Users/Steven/Library/Logs/Homebrew/vmtk/02.make:
      ^
In file included from /tmp/vmtk-20170712-22200-3fuekb/vmtk-1.3.1/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3D.cxx:22:
/tmp/vmtk-20170712-22200-3fuekb/vmtk-1.3.1/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3D.h:63:15: warning: 'RequestData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int RequestData(vtkInformation *, vtkInformationVector **, vtkInformationVector *);
              ^
/usr/local/Cellar/vtk/8.0.0/include/vtk-8.0/vtkPolyDataAlgorithm.h:103:15: note: overridden virtual function is here
  virtual int RequestData(vtkInformation* request,
              ^
3 warnings generated.
4 warnings generated.
`

Whilst `brew install https://gist.githubusercontent.com/lantiga/64b89fbb1f2ce5875bb21558d1599811/raw/b232e485a5deaedbe494670d44f685b053d97b19/vmtk.rb` results in:

`
Last 15 lines from /Users/Steven/Library/Logs/Homebrew/vmtk/02.make:
      ^
In file included from /tmp/vmtk-20170712-28211-188bc3l/vmtk-1.3.2/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3D.cxx:22:
/tmp/vmtk-20170712-28211-188bc3l/vmtk-1.3.2/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3D.h:63:15: warning: 'RequestData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int RequestData(vtkInformation *, vtkInformationVector **, vtkInformationVector *);
              ^
/usr/local/Cellar/vtk/8.0.0/include/vtk-8.0/vtkPolyDataAlgorithm.h:103:15: note: overridden virtual function is here
  virtual int RequestData(vtkInformation* request,
              ^
4 warnings generated.
3 warnings generated.
`

Really grateful for your help.
Steven

**Comment by deparis** [comment]
Quick fix:

`brew uninstall vmtk`
`brew cleanup`

You have to change the git version inside the file vmtk.rb. First download it: 

`wget https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb`

Then edit vmtk.rb, 3rd and 4th line
`url "https://github.com/vmtk/vmtk.git" `
`version "1.4.1" `

(for example). And then install vmtk:
`brew install --build-from-source vmtk.rb`

General fix: This has to be fixed by the maintainers.

**Comment by thangamnatarajan** [comment]
@lantiga @deparis Still the same error:
`brew install --build-from-source vmtk.rb 
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://github.com/vmtk/vmtk.git
Updating /Users/thangam/Library/Caches/Homebrew/vmtk--git
==> Checking out branch master
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/vmtk/1.4.1_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LA
==> make
Last 15 lines from /Users/thangam/Library/Logs/Homebrew/vmtk/02.make:
In file included from /tmp/vmtk-20171023-49798-1xcbrss/build/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3DPython.cxx:11:
/tmp/vmtk-20171023-49798-1xcbrss/vtkVmtk/ComputationalGeometry/vtkvmtkVoronoiDiagram3D.h:63:15: warning: 'RequestData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual int RequestData(vtkInformation *, vtkInformationVector **, vtkInformationVector *);
              ^
/usr/local/Cellar/vtk/8.0.1/include/vtk-8.0/vtkPolyDataAlgorithm.h:103:15: note: overridden virtual function is here
  virtual int RequestData(vtkInformation* request,
              ^
3 warnings generated.
3 warnings generated.
[ 46%] Linking CXX shared library ../../bin/libvtkvmtkComputationalGeometryPythonD.dylib
cd /tmp/vmtk-20171023-49798-1xcbrss/build/vtkVmtk/ComputationalGeometry && /usr/local/Cellar/cmake/3.9.4_1/bin/cmake -E cmake_link_script CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/link.txt --verbose=1
/usr/bin/g++    -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 -dynamiclib -Wl,-headerpad_max_install_names -Wl,-dylib_file,/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib:/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib  -o ../../bin/libvtkvmtkComputationalGeometryPythonD.dylib -install_name /tmp/vmtk-20171023-49798-1xcbrss/build/bin/libvtkvmtkComputationalGeometryPythonD.dylib CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkAppendFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCapPolyDataPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineAttributesFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBifurcationVectorsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBifurcationReferenceSystemsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBranchExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineBranchGeometryPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineEndpointExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineGeometryPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineReferenceSystemAttributesOffsetPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSmoothingPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSphereDistancePython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSplitExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineSplittingAndGroupingFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkCenterlineUtilitiesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkBoundaryReferenceSystemsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkInternalTetrahedraExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkMergeCenterlinesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkMinHeapPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkNonManifoldFastMarchingPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkNonManifoldSteepestDescentPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyBallPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyBallLinePython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyBallModellerPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBifurcationSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBifurcationProfilesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBoundaryExtractorPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBranchSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataBranchUtilitiesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlinesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineGroupsClipperPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineAbscissaMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineAngularMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineProjectionPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataCenterlineSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataFlowExtensionsFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataDistanceToCenterlinesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataLineEmbedderPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataLocalGeometryPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataPatchingFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataReferenceSystemBoundaryMetricFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataScissorsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkPolyDataStretchMappingFilterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkReferenceSystemUtilitiesPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkSimplifyVoronoiDiagramPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkSteepestDescentLineTracerPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkSteepestDescentShooterPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkUnstructuredGridCenterlineGroupsClipperPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkUnstructuredGridCenterlineSectionsPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkVoronoiDiagram3DPython.cxx.o CMakeFiles/vtkvmtkComputationalGeometryPythonD.dir/vtkvmtkComputationalGeometryPythonInitImpl.cxx.o  -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenCL.framework  -L/usr/local/lib  -L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries  -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenCL.framework -Wl,-rpath,/usr/local/lib ../../bin/libvtkvmtkComputationalGeometry.dylib /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/Python /usr/local/Cellar/vtk/8.0.1/lib/libvtkFiltersGeneralPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonComputationalGeometryPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkFiltersCorePython27D-8.0.1.dylib ../../bin/libvtkvmtkCommon.dylib /System/Library/Frameworks/Python.framework/Versions/2.7/Python /usr/local/Cellar/vtk/8.0.1/lib/libvtkWrappingTools-8.0.a /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonExecutionModelPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonDataModelPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonTransformsPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonMiscPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonMathPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonSystemPython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonCorePython27D-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkWrappingPython27Core-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkFiltersGeneral-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonComputationalGeometry-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkFiltersCore-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonExecutionModel-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonDataModel-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonTransforms-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonMisc-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonMath-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonSystem-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtkCommonCore-8.0.1.dylib /usr/local/Cellar/vtk/8.0.1/lib/libvtksys-8.0.1.dylib 
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenCL.framework'
[ 46%] Built target vtkvmtkComputationalGeometryPythonD`
`make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!`

**Comment by kkhuang1990** [comment]
@deparis  @stevenjgilmore  thanks for your sharing. your solution works for me. I further made some other modifications as listed below. 
First, my brew --config is as below:
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3cc0e7f0fefbd6dfb9b4bbcb401b3a7d5de9bd41
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.8.0_121
macOS: 10.13-x86_64
Xcode: 9.0.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11
Since I created a link to link Python: /usr/local/opt/python/libexec/bin/python to /usr/local/bin/python . Don't worry about the Python path here, it is totally ok if your python path is /usr/local/bin/python

Then I also made some revision of the vmtk.rb file as below:
first download the vmtk.rb file using
wget https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb
modifications are made as below:
line 4-5:
- url "https://github.com/vmtk/vmtk/archive/v1.3.2.tar.gz"
- version "1.3.2"
+ url "https://github.com/vmtk/vmtk.git"
+ version "1.4.1"
line 28-29
- python_executable = `which python`.strip if build.with? "python"
- python_executable = `which python3`.strip if build.with? "python3"
+ python_executable = "/usr/local/bin/python" (it depends on which python you use)
line 41:
- args << "-DVTK_DIR=#{HOMEBREW_CELLAR}/vtk/7.1.0"
+ args << "-DVTK_DIR=#{HOMEBREW_CELLAR}/vtk/8.0.1" (when run 'brew install vmtk, the latest vtk will be installed as well. you need to check the vtk version based on your vkt installation'). 

Then install vmtk:
brew uninstall vmtk
brew cleanup
brew install --build-from-source vmtk.rb

After installing the vmtk successfully, check the brew information of vmtk:
>> brew info vmtk
vmtk: stable 1.4.1, HEAD
The Vascular Modeling Toolkit
http://www.vmtk.org
/usr/local/Cellar/vmtk/1.4.1_1 (535 files, 22.7MB) *
  Built from source on 2017-10-28 at 05:08:28
From: /usr/local/opt/vmtk/.brew/vmtk.rb
==> Dependencies
Build: cmake ✔
Required: vtk ✔, insightToolkit ✔
==> Requirements
Build: git ✔
Required: python ✔
Optional: python3 ✔
==> Options
--with-python3
	Build with python3 support
--HEAD
	Install HEAD version

Hope this can help you guys.

**Comment by lassoan** [comment]
Build issues should be fixed now. Windows, linux, macOS wheels are now published on PyPI for 1.5.0.
